### ISSUE TITLE
Schedule entries without actions "run forever"

### ISSUE THREAD

**Issue by hmh** [schoenw/lmapd#14]
The runner depends on a child exiting to do the schedule cleanup (remove schedule from RUNNING state if every action is done).   A comment in lmapd_cleanup() says otherwise, but nothing in the event loop is calling lmapd_cleanup() -- instead, it is being called from a signal handler context for SIGCHLD.

This means a schedule that has no actions will never leave the RUNNING state once it runs.  And that also means it will cause lmapd to issue warnings if it tries to run again, e.g., because it was driven by a recurring event.

It would make a lot more sense for schedules with no actions to end immediately (with a successful state!), unless the LMAP model defines the opposite very explicitly.  Whether such a schedule would be useful at all, is up for discussion though.

If the schedule has actions and all of them are suppressed (or for any other reason they do not cause a fork() to happen), this might well cause lmapd to misbehave.

**Comment by schoenw** [comment]
This should be fixed in 1bb86cefb71e2fe98780601623605375ded5b02e.
