### ISSUE TITLE
-Wall -Werror with new compiilers trigger build issues

### ISSUE THREAD

**Issue by hmh** [schoenw/lmapd#5]
The use of -Wall -Werror is known to cause problems when compilers add new warnings, and at least one such issue is happening right now with gcc 6.3 (Debian stable):

```
 /tmp/x/lmapd/src/csv.c:24:19: warning: ‘delimiter’ defined but not used [-Wunused-const-variable=]
 static const char delimiter = ';';
```

This can be worked around by removing -Werror in the toplevel CMakeLists.txt.

**Comment by schoenw** [comment]
Fixed in commit ff04bf4bbae2d84537539f548132fc4077486ed4.
