### ISSUE TITLE
Outdated YANG models

### ISSUE THREAD

**Issue by hmh** [schoenw/lmapd#6]
The YANG models should be updated to their latest "RFC-blessed" versions, and any relevant changes (if any) should be addressed in the lmapd code.

This is somewhat relevant because lmpad is a reference implementation...

**Comment by schoenw** [comment]
I have replaced the YANG modules with the RFC versions as published by IANA. I did not spot any changes that affect the code when I diffed the YANG modules hence I assume commit d408e9b7265bd0de784feebeb72f579003160c53 closes the issue.
