### ISSUE TITLE
Remove suppress-by-default

### ISSUE THREAD

**Issue by hmh** [schoenw/lmapd#8]
(whishlist)

Some areas of the code still handle "suppress-by-default" (regardless of it being fully implemented or not in the code as a whole).

This is functionality that was present in drafts, but was dropped from the final RFCs, so it should be removed from the reference implementation.

**Comment by schoenw** [comment]
I have moved all left overs of "suppress-by-default" in commit 32558473af3c947b17c0445859cb527cf31da349.
